### PR TITLE
refactor: include filepaths if attaching multple text files

### PR DESCRIPTION
**Pull request by sigoden**
include filepaths if attaching multple text files

```
$ aichat --file ./file1 --file ./file2 -- compare
 compare
`./file1`:
~~~~~~
This is file1
~~~~~~
`./file2`:
~~~~~~
This is file2
~~~~~~
```

### CODE REVIEW

**Comment by Konfekt** [comment]
Somehow only `--file=$path` is accepted, but not `-f $path` or `--file $path` to attach the file content on 0.15.0; is this intentional?

**Comment by sigoden** [comment]
@Konfekt I didn't find the problem you mentioned.

**Comment by Konfekt** [comment]
I should have said that this is on Linux inside Zsh. 
For example, inside `~/`,

```sh
$ aichat -f .profile check syntax
Welcome to aichat 0.15.0
Type ".help" for more information.
respondent> 

$ aichat -f=.profile check syntax 
The syntax of your script appears to be correct, assuming it is intended to be used within a Bash shell script.
```

I would have expected both commands to work similarly.

Note that `-f=` is not documented, so maybe it does something wrong, but for me this is more useful.

**Comment by sigoden** [comment]
you have to use `--` to split file args and text args.
```diff
-- $ aichat -f=.profile check syntax 
++ $ aichat -f=.profile -- check syntax 
```

Originally intended to be consistent with REPL `.file` command
```
> .file
Usage: .file <files>...  -- <text>...
```
Now it seems like there is a misunderstanding, I would make `-f/--file` accept a value every time in the next version.

**Pull request merged**
