### PR TITLE
add shell completion scripts

### PR DESCRIPTION
**Pull request by Konfekt**
addresses https://github.com/sigoden/aichat/issues/392

### CODE REVIEW

**Comment by sigoden** [comment]
Can you place the completion script in the `shell/completions` folder? @Konfekt

**Comment by sigoden** [comment]
## Except for bash, the completion scripts of other shells do not work properly.

### zsh: throw error
```sh
_arguments:comparguments:327: can only be called from completion function
```

### fish: throw error
```
mplete: Expected a string, but found a redirection
no auto <max-width>
        ^
aichat --help                   aichat -complete: no auto <max-width>: contains a syntax error
```
Even if I delete the problematic line and reload it, there is still no completion.

### nushell: throw error
```
Error: nu::parser::missing_positional

  × Missing required positional argument.
   ╭─[.../aichat/scripts/shell-completion/aichat-completion.nu:5:68]
 4 │ 
 5 │ let models = (aichat --list-models | lines | escape-colons-in-array)
   ·                                                                    ▲
   ·                                                                    ╰── missing array
 6 │ let roles = (aichat --list-roles | lines | escape-colons-in-array)
   ╰────
  help: Usage: escape-colons-in-array <array> . Use `--help` for more information.
  ```
  
### powershell: no completion

**Comment by sigoden** [comment]
When scripts are loaded, they initialize the variables `$model`, `$roles`, and `$session`. This approach is not recommended as it can prolong script loading times and slow down shell startup.

**Comment by Konfekt** [comment]
I think you tested against an old commit. As discussed in https://github.com/sigoden/aichat/issues/392#issuecomment-2052209528 the wrap completion was flawed and fixed. However, I am no expert at all these shells as I only use bash and zsh, which should work

**Comment by Konfekt** [comment]
I am sorry, my bad, the push didn't arrive, but only now

**Comment by Konfekt** [comment]
> When scripts are loaded, they initialize the variables $model, $roles, and $session. This approach is not recommended as it can prolong script loading times and slow down shell startup.

At some point it has to be done. If Zsh is smart enough, it loads the completion script only if the command is invoked the first time.

**Comment by Konfekt** [comment]
For zsh it was crucial to escape the colons, maybe for other shells not. I removed this for nushell.

**Comment by sigoden** [comment]
I still think that model, role, and session should be loaded on demand.

Executing only once per shell session is not ideal; it can negatively impact performance.
Executing once globally will result in old data being used, which is also considered poor practice.

**Comment by Konfekt** [comment]
Well, is it as simple as

```zsh
if (( CURRENT != 2 )); then
  return
fi
```

?

**Comment by Konfekt** [comment]
As I understand you, Zsh (and others ?) source these completions script on every startup. This check quits if it's not invoked for completing an argument.

**Comment by sigoden** [comment]
You may refer to https://github.com/sharkdp/bat/tree/master/assets/completions
See how it completes `--theme`
https://github.com/sharkdp/bat/blob/master/assets/completions/bat.bash.in#L114-L119
https://github.com/sharkdp/bat/blob/master/assets/completions/bat.fish.in#L204

**Comment by Konfekt** [comment]
But 

```zsh
if (( CURRENT < 2 )); then
  return
fi
```

works fine

**Comment by Konfekt** [comment]
Bash, ZSH, Powershell work now. Fish and Nushell I have no access to. Maybe you or @ezuk can give hints

**Comment by Konfekt** [comment]
After all, tedious was the special character `:` that had to be escaped in ZSH, but this complication does not occur in the other shells ?!

**Comment by sigoden** [comment]
I was originally going to make changes directly on your PR, but I realized later that there were too much change, so I created a new PR #411  instead.

1. One reason is that since aichat is based on `clap`, using `clap-complete` to generate the completion script makes it easier to synchronize updates later on.

2. Another reason is that there are still quite a few issues with your current completion script:
  - **bash:** Issues with colons when completing models.
  - **nushell:** Throw error on load, and the completion values lack descriptions.
  - **powershell:**Every time completion is triggered, the script run `--list-{models,roles,sessions}` , and the completion values lack descriptions.
    
Thanks again for your contribution.

**Comment by Konfekt** [comment]
Oh, I didn't know about clap-complete. That's easier. I just wrote the ZSH script and tried to port it.

**Pull request closed without merging**
