### PR TITLE
feat: support conversation

### LINKED ISSUE #40: [Feature Request] chat/session mode (i.e. back and forth conversation)
Currently, aichat behaves in a one-off request/response manner -- it has no "context" info.

e.g.

```
> show me some haskell code to print fibonacci numbers
Here is the Haskell code to print the first n Fibonacci numbers:

────────────────────
fib :: Int -> [Int]
fib n = take n fibList
  where fibList = 0 : 1 : zipWith (+) fibList (tail fibList)

main :: IO ()
main = do
    putStrLn "Enter the number of Fibonacci numbers to print:"
    n <- readLn
    putStrLn $ "The first " ++ show n ++ " Fibonacci numbers are: "
    print $ fib n
────────────────────

> now convert it to python
Sorry, I'm an AI language model and I would need to see the original code to convert it to Python. 
Can you please provide more context or the original code you would like to convert?
```

We have `chat` in our name, so it'd be nice if it can mimic a real chatting bot (a la ChatGPT) who can have a conversation.  Implementation-wise (from a high level view), we can just extend the `messages` sent to the OpenAI API with every input & output we've got so far.

As for the UI, we probably can make it default in interactive mode, while adding some extra commands  like `.clear session`,  `.mode chat`, etc.

### PR DESCRIPTION
**Pull request by sigoden**
```
〉.conversation

＄.clear conversation

〉
```

close #40

### CODE REVIEW

**Comment by XOKP** [comment]
Is it possible to add a CLI option to enter the conversation mode directly?

**Comment by sigoden** [comment]
@XOKP #55 solved this

**Comment by XOKP** [comment]
Thank you so much for implementing it so so fast! Your hard work and responsiveness to suggestions are truly appreciated.

Just one additional thought: since this is a system-wide configuration, it might be even more useful if we could also set it based on specific roles rather than just as a global setting.

I'm grateful for everything you've done, thanks again for all your effort on this project.

**Comment by sigoden** [comment]
Semantically, role is only related to gpt, not to tui operation, I will not do this.

**Pull request merged**
