### PR TITLE
feat: support RAG

### PR DESCRIPTION
**Pull request by sigoden**
## Screenshot

image

## REPL

```
.rag <name>             Init a rag
.info rag               View rag info
.exit rag               Leave the rag 
```

## TODO

- [x] Process numerous document chunks with multiple calls to the embeddings API
- [x] Support more embedding models (openai, cohere, mistral, ollama, vertexai, qianwen)
- [x] Show the progress of adding paths
- [x] Support non-text formats like pdf, docx, epub, ipynb

### CODE REVIEW

**Comment by dtrckd** [comment]
Hi,

That sounds great! Here are some insights:

- The most critical aspect is the chunking strategy, as it significantly impacts the quality of the answers. Therefore, having a flexible abstraction to easily change this strategy is important for both developers and users. For example, you could have multiple strategies depending on the document format and a "chunking_strategy" configuration.
- The number of chunks to return is also crucial and depends on both the chunk size and the model's context window. Keep in mind that some models' performance degrades more than others with large prompts.
- One heuristic to improve search quality is to augment chunks with additional context. For instance, if a chunk is located in a sub-section of a document, adding the document and section titles can improve the relevancy of the found chunks.
- Handling a **rag-conversation mode** is challenging. Determining which questions are pertinent for the research is not straightforward. A simple initial approach might be concatenating some of the previous questions. Some have used another LLM call to reformulate the question given the history to address this issue.

**Comment by sigoden** [comment]
@dtrckd Thank you for your suggestions.

1. Regular users wouldn't know what `chunk_strategy` is. we choose `RecursiveCharacterTextSplitter` (which is also the default splitter in anything-llm, jan, etc.) because it supports adapts to the document format.
2. There's already a configuration option called `rag_top_k`.
3. From an engineering standpoint, it's difficult to implement. Extracting `additional context` (like section, title) from documents is a complex task.
4. What is `rag-conversation mode`?

**Comment by sigoden** [comment]
Methods to Improve Retrieval Accuracy:

- Hybrid Search: Vector search combined with text search
- MultiVector Retriever
- Rerank

**Comment by dtrckd** [comment]
1. ok I see. It's just that at some point, we could have a knowledge base that we want to chunkify with a different strategy (codebase file for exemple, html/xml doc...), for a future iteration maybe.
2. ok.
3. Yes, and it is closely related to the first point.
4. When you do RAG in a session (what I called conversation mode).

**Comment by sigoden** [comment]
@dtrckd You can already use RAG within the session.

**Comment by dtrckd** [comment]
How do you build search query within a session ?

**Comment by sigoden** [comment]
@dtrckd No special treatment. If there is a session, bring the chat history, if there is a RAG, bring the retrieval contenxt.

**Comment by dtrckd** [comment]
> @dtrckd No special treatment. If there is a session, bring the chat history, if there is a RAG, bring the retrieval contenxt.

By "chat history" if you mean all the augmented prompt + the answer, I think it will quickly defeat the embedding search.
From my experience, when the query is too large the relevancy of semantic search drops...

**Comment by sigoden** [comment]
No, chat history will not be included in embedding search.

**Comment by marioseixas** [comment]
holy shit, incredible work

congratz, man, you are very talented

**Pull request merged**
